# Generated by Django 4.2.11 on 2024-05-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_filmwork_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genrefilmwork',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='created',
            new_name='created_at',
        ),
    ]
